version: '3.6'

services:
  # nginx
  nginx:
    container_name: 'aiviet-nginx'
    image: 'nginx:1.14'
    ports:
      - 80:80
    volumes:
      - ./backend:/srv:rw
      - ./docker/nginx/conf/site-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - 'php'

  # php
  php:
    container_name: 'aiviet-php'
    build: './docker/php'
    working_dir: '/srv'
    command: bash -c 'composer install && php-fpm'
    volumes:
      - ./backend:/srv

  # db
  db:
    container_name: 'aiviet-db'
    build: './docker/db'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
